In [ ]:
from bs4 import BeautifulSoup
import requests
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
import pandas as pd
import numpy as np
import datetime
from datetime import datetime

In [ ]:
#EXECUTE ONLY ONCE TO SCRAPE WEATHER DATA
driver = webdriver.Safari(executable_path ='/usr/bin/safaridriver')
df = pd.DataFrame(columns=['time', 'temp', 'dew_point', 'humidity', 'wind', 'wind_speed', 'wind_gust', 'pressure', 'precip', 'condition', 'date'])

for i in range(1,13):
    days_in_month = 0
    if i in [1,3,5,7,8,10,12]:
        days_in_month = 32
    elif i in [4,6,9,11]:
        days_in_month = 31
    elif i in [2]:
        days_in_month = 29
    for j in range(1,days_in_month):
        date = f'{j}.{i}.2017'
        print(date)
        url = f'https://www.wunderground.com/history/daily/KMDW/date/2017-{i}-{j}'
        driver.get(url)
        time.sleep(3)
        html = driver.page_source
        soup = BeautifulSoup(html, 'html.parser')
        table = soup.find('table', attrs={'class': 'mat-table cdk-table mat-sort ng-star-inserted' })
        table_rows = table.find_all('tr')
        l = []
        for tr in table_rows:       
            td = tr.find_all('td')
            row = [tr.text for tr in td]
            if row:
                row.append(f'{j}.{i}.2017')
            l.append(row)
            l = list(filter(None, l))
        for k in l:
            df.loc[len(df)] = k
            
            

driver.quit()

In [ ]:
df.tail()

In [149]:
#save scraped data in csv
df.to_csv('./data/weather_data_date.csv', index = False)

In [233]:
#load scraped data for further processing
df = pd.read_csv('./data/weather_data_date.csv')

In [234]:
#filter out all datapoints that have been collected outside of the hourly (XX:53 AM/PM) weather measurements 
tuple = ('53 AM', "53 PM")
df_hourly_measurement = df[df['time'].str.endswith(tuple)]
len(df_hourly_measurement)

8749

In [235]:
df_hourly_measurement = df_hourly_measurement.reset_index()
df_hourly_measurement.head()

,index,time,temp,dew_point,humidity,wind,wind_speed,wind_gust,pressure,precip,condition,date
0,0,1:53 AM,25 °F,18 °F,75 °%,W,3 °mph,0 °mph,29.33 °in,0.0 °in,Fair,1.1.2017
1,1,2:53 AM,25 °F,18 °F,75 °%,CALM,0 °mph,0 °mph,29.34 °in,0.0 °in,Fair,1.1.2017
2,2,3:53 AM,25 °F,19 °F,78 °%,SSW,5 °mph,0 °mph,29.36 °in,0.0 °in,Fair,1.1.2017
3,3,4:53 AM,24 °F,18 °F,77 °%,SSW,7 °mph,0 °mph,29.37 °in,0.0 °in,Fair,1.1.2017
4,4,5:53 AM,22 °F,17 °F,82 °%,SSW,6 °mph,0 °mph,29.39 °in,0.0 °in,Fair,1.1.2017

In [236]:
df_hourly_measurement['time'] = pd.to_datetime(df_hourly_measurement['time'], format='%I:%M %p').dt.strftime('%H:%M')
df_hourly_measurement['date'] = pd.to_datetime(df_hourly_measurement['date'], format='%d.%m.%Y').dt.strftime('%Y-%m-%d')
date = df_hourly_measurement['date']
df_hourly_measurement.drop(labels=['date'], axis=1,inplace = True)
df_hourly_measurement.insert(1, 'date', date)
df_hourly_measurement.drop('index', axis=1, inplace = True)
df_hourly_measurement.drop('wind', axis=1, inplace = True)
print(len(df_hourly_measurement))
df_hourly_measurement.head()

8749

,date,time,temp,dew_point,humidity,wind_speed,wind_gust,pressure,precip,condition
0,2017-01-01,01:53,25 °F,18 °F,75 °%,3 °mph,0 °mph,29.33 °in,0.0 °in,Fair
1,2017-01-01,02:53,25 °F,18 °F,75 °%,0 °mph,0 °mph,29.34 °in,0.0 °in,Fair
2,2017-01-01,03:53,25 °F,19 °F,78 °%,5 °mph,0 °mph,29.36 °in,0.0 °in,Fair
3,2017-01-01,04:53,24 °F,18 °F,77 °%,7 °mph,0 °mph,29.37 °in,0.0 °in,Fair
4,2017-01-01,05:53,22 °F,17 °F,82 °%,6 °mph,0 °mph,29.39 °in,0.0 °in,Fair

In [237]:
#Identify Duplicates
duplicate_counts = df_hourly_measurement.groupby(['date', 'time']).size().reset_index(name='count')
duplicate_counts = duplicate_counts[duplicate_counts['count'] > 1]

print(duplicate_counts)

            date   time  count
2010  2017-03-25  19:53      2
2036  2017-03-26  23:53      2
7188  2017-10-28  00:53      2
7212  2017-10-29  02:53      2
7378  2017-11-05  00:53      2

In [238]:
#Drop Duplicates
df_hourly_measurement.drop_duplicates(subset=['date','time'], keep='first', inplace=True)
print(len(df_hourly_measurement))

8744

In [239]:
#Check for duplicates again, to see if it worked
duplicate_counts = df_hourly_measurement.groupby(['date', 'time']).size().reset_index(name='count')
duplicate_counts = duplicate_counts[duplicate_counts['count'] > 1]
print(duplicate_counts)

Empty DataFrame
Columns: [date, time, count]
Index: []

In [240]:
#Sort array, since 00:53 was always on the end of a day, even if it has to be first
# Reset index since after sorting it might change 
df_hourly_measurement = df_hourly_measurement.sort_values(by=['date', 'time'])
df_hourly_measurement.reset_index(inplace = True, drop = True)
df_hourly_measurement.head()

,date,time,temp,dew_point,humidity,wind_speed,wind_gust,pressure,precip,condition
0,2017-01-01,00:53,33 °F,24 °F,70 °%,8 °mph,0 °mph,29.45 °in,0.0 °in,Partly Cloudy
1,2017-01-01,01:53,25 °F,18 °F,75 °%,3 °mph,0 °mph,29.33 °in,0.0 °in,Fair
2,2017-01-01,02:53,25 °F,18 °F,75 °%,0 °mph,0 °mph,29.34 °in,0.0 °in,Fair
3,2017-01-01,03:53,25 °F,19 °F,78 °%,5 °mph,0 °mph,29.36 °in,0.0 °in,Fair
4,2017-01-01,04:53,24 °F,18 °F,77 °%,7 °mph,0 °mph,29.37 °in,0.0 °in,Fair

In [241]:
print('Number of missing Hours: ',(365*24)- len(df_hourly_measurement))

Number of missing Hours:  16

In [242]:
# Create reference dataframes for date and time: They contain 24 hours for each day and will be used to compare with our dataframe 
# Thus helping to identify missing hours

ref_dates = pd.date_range(start = "2017-01-01", end = "2017-12-31", freq = 'D')
ref_times = pd.date_range(start = "00:53", end = "23:53", freq = 'H').time
#Create 24 date-time couples, for every date
ref_df = pd.DataFrame([(date,time) for date in ref_dates for time in ref_times], columns =['date', 'time'])
#convert columns for later combination
ref_df['time'] = ref_df['time'].astype(str)
ref_df['date'] = ref_df['date'].dt.strftime('%Y-%m-%d')
ref_df['date_time'] = pd.to_datetime(ref_df['date'] + ' ' + ref_df['time'])
print(len(ref_df))
ref_df.head()

8760

         date      time           date_time
0  2017-01-01  00:53:00 2017-01-01 00:53:00
1  2017-01-01  01:53:00 2017-01-01 01:53:00
2  2017-01-01  02:53:00 2017-01-01 02:53:00
3  2017-01-01  03:53:00 2017-01-01 03:53:00
4  2017-01-01  04:53:00 2017-01-01 04:53:00

In [243]:
df_hourly_measurement['date_time'] = pd.to_datetime(df_hourly_measurement['date'] + df_hourly_measurement['time'], format='%Y-%m-%d%H:%M')
df_hourly_measurement.head()

,date,time,temp,dew_point,humidity,wind_speed,wind_gust,pressure,precip,condition,date_time
0,2017-01-01,00:53,33 °F,24 °F,70 °%,8 °mph,0 °mph,29.45 °in,0.0 °in,Partly Cloudy,2017-01-01 00:53:00
1,2017-01-01,01:53,25 °F,18 °F,75 °%,3 °mph,0 °mph,29.33 °in,0.0 °in,Fair,2017-01-01 01:53:00
2,2017-01-01,02:53,25 °F,18 °F,75 °%,0 °mph,0 °mph,29.34 °in,0.0 °in,Fair,2017-01-01 02:53:00
3,2017-01-01,03:53,25 °F,19 °F,78 °%,5 °mph,0 °mph,29.36 °in,0.0 °in,Fair,2017-01-01 03:53:00
4,2017-01-01,04:53,24 °F,18 °F,77 °%,7 °mph,0 °mph,29.37 °in,0.0 °in,Fair,2017-01-01 04:53:00

In [244]:
#convert date_time columns of df_hourly_measurement and ref_df into a list to easily get missing values using .difference function of list
current_dt = df_hourly_measurement['date_time'].tolist()
expected_dt = ref_df['date_time'].tolist()
missing_dt = list(set(expected_dt).difference(current_dt))
df_missing = pd.DataFrame({'date_time': missing_dt})
print(df_missing)

             date_time
0  2017-10-29 00:53:00
1  2017-11-17 20:53:00
2  2017-10-02 23:53:00
3  2017-08-17 00:53:00
4  2017-11-19 13:53:00
5  2017-03-26 02:53:00
6  2017-07-18 04:53:00
7  2017-03-12 00:53:00
8  2017-08-17 01:53:00
9  2017-06-18 23:53:00
10 2017-08-17 03:53:00
11 2017-08-17 02:53:00
12 2017-03-25 23:53:00
13 2017-10-28 20:53:00
14 2017-06-18 22:53:00
15 2017-08-17 04:53:00

In [245]:
# merge df_hourly_measurement together to obtain a dataframe that contains all hours, but still needs to fill all other columns
df_merged = pd.merge(df_hourly_measurement, df_missing, on='date_time', how='outer')
df_merged.sort_values(by='date_time', inplace=True)
df_merged.reset_index(inplace = True, drop = True)
print(len(df_merged))
df_merged.head()

8760

,date,time,temp,dew_point,humidity,wind_speed,wind_gust,pressure,precip,condition,date_time
0,2017-01-01,00:53,33 °F,24 °F,70 °%,8 °mph,0 °mph,29.45 °in,0.0 °in,Partly Cloudy,2017-01-01 00:53:00
1,2017-01-01,01:53,25 °F,18 °F,75 °%,3 °mph,0 °mph,29.33 °in,0.0 °in,Fair,2017-01-01 01:53:00
2,2017-01-01,02:53,25 °F,18 °F,75 °%,0 °mph,0 °mph,29.34 °in,0.0 °in,Fair,2017-01-01 02:53:00
3,2017-01-01,03:53,25 °F,19 °F,78 °%,5 °mph,0 °mph,29.36 °in,0.0 °in,Fair,2017-01-01 03:53:00
4,2017-01-01,04:53,24 °F,18 °F,77 °%,7 °mph,0 °mph,29.37 °in,0.0 °in,Fair,2017-01-01 04:53:00

In [246]:
# get all rows that have NaN values => all, which only have the date_time defined are the added missing values
nan_rows = df_merged[df_merged.isna().any(axis=1)]
print(nan_rows)

     date time temp dew_point humidity wind_speed wind_gust pressure precip  \
1680  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN
2015  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN
2018  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN
4054  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN
4055  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN
4756  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN
5472  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN
5473  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN
5474  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN
5475  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN
5476  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN
6599  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN
7220  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN
7224  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN
7700  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN
7741  NaN  NaN  NaN       NaN      NaN        NaN       NaN      NaN    NaN

     condition           date_time
1680       NaN 2017-03-12 00:53:00
2015       NaN 2017-03-25 23:53:00
2018       NaN 2017-03-26 02:53:00
4054       NaN 2017-06-18 22:53:00
4055       NaN 2017-06-18 23:53:00
4756       NaN 2017-07-18 04:53:00
5472       NaN 2017-08-17 00:53:00
5473       NaN 2017-08-17 01:53:00
5474       NaN 2017-08-17 02:53:00
5475       NaN 2017-08-17 03:53:00
5476       NaN 2017-08-17 04:53:00
6599       NaN 2017-10-02 23:53:00
7220       NaN 2017-10-28 20:53:00
7224       NaN 2017-10-29 00:53:00
7700       NaN 2017-11-17 20:53:00
7741       NaN 2017-11-19 13:53:00

In [247]:
#setting the date and time columns according to the date time
nan_rows['date'] = pd.to_datetime(nan_rows['date_time']).dt.date
nan_rows['time'] = pd.to_datetime(nan_rows['date_time']).dt.strftime('%H:%M')

#filling the other columns with the average values of the previous and following non-NaN value in df_merged
nan_rows = nan_rows.fillna(df_merged.ffill().bfill())
#print(nan_rows)
df_merged.update(nan_rows)

# have everything be in the same format again
df_merged.sort_values(by='date_time', inplace=True)

In [248]:
nan_rows = df_merged[df_merged.isna().any(axis=1)]
print(nan_rows)

Empty DataFrame
Columns: [date, time, temp, dew_point, humidity, wind_speed, wind_gust, pressure, precip, condition, date_time]
Index: []

In [252]:
#
#df_merged.reset_index(drop=True, inplace=True)
print(df_merged.iloc[1678:1704])
#print(df_merged.loc[df_merged['date_time'] == "2017-03-12 00:53:00"])

            date   time   temp dew_point humidity wind_speed wind_gust  \
1678  2017-03-11  22:53  26 °F      3 °F    37 °%     9 °mph    0 °mph
1679  2017-03-11  23:53  26 °F      2 °F    35 °%     6 °mph    0 °mph
1680  2017-03-12  00:53  26 °F      2 °F    35 °%     6 °mph    0 °mph
1681  2017-03-12  01:53  24 °F     -2 °F    32 °%     6 °mph    0 °mph
1682  2017-03-12  02:53  23 °F     -1 °F    35 °%     7 °mph    0 °mph
1683  2017-03-12  03:53  22 °F      1 °F    40 °%     3 °mph    0 °mph
1684  2017-03-12  04:53  21 °F      1 °F    42 °%     6 °mph    0 °mph
1685  2017-03-12  05:53  20 °F      1 °F    44 °%     6 °mph    0 °mph
1686  2017-03-12  06:53  20 °F      2 °F    46 °%     6 °mph    0 °mph
1687  2017-03-12  07:53  23 °F      1 °F    39 °%     7 °mph    0 °mph
1688  2017-03-12  08:53  25 °F      3 °F    39 °%     5 °mph    0 °mph
1689  2017-03-12  09:53  26 °F     -1 °F    31 °%     0 °mph    0 °mph
1690  2017-03-12  10:53  28 °F     -5 °F    24 °%     6 °mph    0 °mph
1691  2017-03-12  11:53  30 °F     -4 °F    23 °%     5 °mph    0 °mph
1692  2017-03-12  12:53  31 °F     -5 °F    21 °%     7 °mph    0 °mph
1693  2017-03-12  13:53  33 °F     -5 °F    19 °%     7 °mph    0 °mph
1694  2017-03-12  14:53  36 °F     -1 °F    21 °%     5 °mph    0 °mph
1695  2017-03-12  15:53  35 °F     -1 °F    22 °%     3 °mph    0 °mph
1696  2017-03-12  16:53  34 °F      4 °F    28 °%    12 °mph   24 °mph
1697  2017-03-12  17:53  32 °F      7 °F    35 °%     8 °mph   23 °mph
1698  2017-03-12  18:53  32 °F     10 °F    40 °%    15 °mph   26 °mph
1699  2017-03-12  19:53  32 °F     15 °F    50 °%    10 °mph   16 °mph
1700  2017-03-12  20:53  32 °F     16 °F    52 °%    13 °mph   16 °mph
1701  2017-03-12  21:53  30 °F     19 °F    64 °%     6 °mph    0 °mph
1702  2017-03-12  22:53  29 °F     22 °F    75 °%     7 °mph    0 °mph
1703  2017-03-12  23:53  28 °F     23 °F    81 °%     9 °mph    0 °mph

       pressure   precip      condition           date_time
1678  29.81 °in  0.0 °in         Cloudy 2017-03-11 22:53:00
1679  29.80 °in  0.0 °in         Cloudy 2017-03-11 23:53:00
1680  29.80 °in  0.0 °in         Cloudy 2017-03-12 00:53:00
1681  29.79 °in  0.0 °in           Fair 2017-03-12 01:53:00
1682  29.79 °in  0.0 °in           Fair 2017-03-12 02:53:00
1683  29.77 °in  0.0 °in           Fair 2017-03-12 03:53:00
1684  29.77 °in  0.0 °in           Fair 2017-03-12 04:53:00
1685  29.77 °in  0.0 °in           Fair 2017-03-12 05:53:00
1686  29.78 °in  0.0 °in           Fair 2017-03-12 06:53:00
1687  29.78 °in  0.0 °in           Fair 2017-03-12 07:53:00
1688  29.80 °in  0.0 °in           Fair 2017-03-12 08:53:00
1689  29.81 °in  0.0 °in           Fair 2017-03-12 09:53:00
1690  29.79 °in  0.0 °in  Mostly Cloudy 2017-03-12 10:53:00
1691  29.77 °in  0.0 °in  Mostly Cloudy 2017-03-12 11:53:00
1692  29.77 °in  0.0 °in  Mostly Cloudy 2017-03-12 12:53:00
1693  29.74 °in  0.0 °in  Mostly Cloudy 2017-03-12 13:53:00
1694  29.71 °in  0.0 °in  Mostly Cloudy 2017-03-12 14:53:00
1695  29.69 °in  0.0 °in         Cloudy 2017-03-12 15:53:00
1696  29.66 °in  0.0 °in         Cloudy 2017-03-12 16:53:00
1697  29.65 °in  0.0 °in         Cloudy 2017-03-12 17:53:00
1698  29.64 °in  0.0 °in         Cloudy 2017-03-12 18:53:00
1699  29.65 °in  0.0 °in         Cloudy 2017-03-12 19:53:00
1700  29.65 °in  0.0 °in         Cloudy 2017-03-12 20:53:00
1701  29.65 °in  0.0 °in     Light Snow 2017-03-12 21:53:00
1702  29.65 °in  0.0 °in     Light Snow 2017-03-12 22:53:00
1703  29.62 °in  0.0 °in     Light Snow 2017-03-12 23:53:00